session_name: session_dataset2d
windows:
  - window_name: dev window
    layout: tiled
    shell_command_before:
       - cd .. # run as a first command in all panes
    panes:
      # - shell_command: # pane no. 1
      #     - cd /var/log # run multiple commands in this pane
      #     - ls -al | grep \.log
      - python main.py --method walker_1   --dimension_dataset 2  --weight_soft_cost 0    --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method walker_2   --dimension_dataset 2  --weight_soft_cost 0    --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi

      - python main.py --method UU         --dimension_dataset 2  --weight_soft_cost 0    --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method UU         --dimension_dataset 2  --weight_soft_cost 10   --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method UU         --dimension_dataset 2  --weight_soft_cost 100  --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method UU         --dimension_dataset 2  --weight_soft_cost 1000 --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi

      - python main.py --method UP         --dimension_dataset 2  --weight_soft_cost 0    --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method UP         --dimension_dataset 2  --weight_soft_cost 10   --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method UP         --dimension_dataset 2  --weight_soft_cost 100  --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method UP         --dimension_dataset 2  --weight_soft_cost 1000 --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi

      - python main.py --method DC3        --dimension_dataset 2  --weight_soft_cost 0    --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method DC3        --dimension_dataset 2  --weight_soft_cost 10   --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method DC3        --dimension_dataset 2  --weight_soft_cost 100  --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
      - python main.py --method DC3        --dimension_dataset 2  --weight_soft_cost 1000 --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi

      - python main.py --method PP         --dimension_dataset 2  --weight_soft_cost 0    --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi

      - python main.py --method Bar        --dimension_dataset 2  --weight_soft_cost 0    --test False  && if [[ $(tmux list-panes | wc -l) -eq 1 ]]; then tmux kill-session; else exit; fi
